apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  selector:
    app: api
  ports:
  - port: 8000      # Cluster internal port
    targetPort: 8000 # Must match containerPort and ENV PORT
    nodePort: {{ .Values.service.nodePort }} # Will be 30002
