---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgCnDKJuWgRjvV/AYWdlPfRCkVz64pF/6a4OeMAU3zYKgU1MHnK1sJZGCcwwV4S7UdpdYc4mkTvnCocnR19m1O6Dbs9BD2uXRuSuRa3R9XBGzPlihSwQnQpFxXwgS9kJgtwoI6RIhjBNLAnkdCp+iwhooSmdHFzgqpAMVs7R45WQHLJvVRsBXPP+1b1I0oI9X/3Bcp40wcRumj97M1uEAc2MAqa6PxRed3ZbaGe7+CzAxbO+KaMVzkDYnixe/KzZve9WLIXEQ9C1UdF6F3GVoaiCYc6mT1FwLN17gCIcv6l/iN7PNhIVpGpzhLWfwShsArUFq8H2dsOXV2bF8vGw0cW6jn0hC5XAIHdYePsPTsLO5pjbA3kZalq86YMN9qyZK8cdvQ3ooQo0H5CQVAVRHtUf69PgGkH4omQmGs1qm2njcBsFpUGR5aE68ZHvtrA8rdVSiZ4nC95DU2JxMHV2KAEd+vNWgOF3MGVayOFP26Fzwdba+aZxHD+LVzHxCh7yxUt6uhn6z6QKPRy5UuHqL06ix2uuzG+MqdCToPUGirf4uPkq3FrZ8jYlSQXXTMe1cvVyNezTNKbXJTl8CoIBEV7gkKfxqQTkVwiqTQAEBD2ABobESP/TZ7zlbA/y239/28rJ++a2l+oyhJ7+oW0DazUe61Qnxevtx9v711RciH05pb98/NugZraQ0zomwJU2a4VKwOLZhtrU4BhMxQ==
    username: AgDamSax2ac0DlK1dpv0iQJXZH0k/8KIfrSS8xlmJZIYjDFXe2sFyepSXaCqQhZR/n3MZk7+V5LNm4bOSkVhVh3Tk0tu3qom+GoNch//2d0CzCp+2uBFyhGMArCg2YEML2TTZCd4eFXaPxnydZZQSeYVly4U2MljRKkawREx2bKwWkrOYL7X+VtLptjB0AJgrmq/NcyVAF+ldFTxq1vUQW4qThA/nnU0pR7BlSKWC3QL4IfNl7wDX7V1nqlIVwgdteRvVdZeUqQlH2nrTIbcAg5/6QRESJc9EQihCEsvsK6CTpVx5MzXbb7lEXs3rOdS6gtO4RGWICdND/WQipTC2zf27ytUmLOwprFZUqQDul3vHJb8CrEMuqMpmE54KbjHaIluZ99Ipijko9PqNVJAEXQsilk78dO6CM5InNMPJBhzma/ylDeajlbAv/ReHo/hkPsqwcw09ER8zJmr/10deZdy9Y3VSvaJhv8SQAYPBxL7ZsGwEaDF2lypBY266EEqCeq6vU+WkoqV5msla3ZfkGrTBZYt8YyjDWObR6lA8i4Dho1kpOmBPi+oIcFl1nliPzJI19VbNwSDFA/SQsPIUTkMcLpsatGBMV+oWTJtkzePjSrbkbT0iumzcdsr390+KZvb/ClBJgB6VQf81f2L9jeYhAC3C3t6udUDxmfZc5BVzdowTqEpDEd+nE8RG/jqTZlkLoMaIA==
  template:
    metadata:
      name: demo-secret
      namespace: default
