---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: app
spec:
  encryptedData:
    password: AgBVJsev1vQJzHyZe3qEHZ/B146JEVacaivef/AdqiG0tbRqZowz5tT0aCk1Wlfp4VpCnqOlgbMzcp4+/x4G9zNgN80OwZVguzgpPBM9xIkOvece2S9JfvKX6y0svXkC9k9OQ8di/mB0spzDAunO4CA9xA+j9rp2Ow0nXIKKvqEQpiHGcJU25/o6OeVNGZGv6FHtC8DqHpy8ACl4a8fSQ7kYpioMspj0CWdjuP2EXdxXtgY+SC3NnklSL2eG8L7O2v0L0gDMNdfsOUBJejaBEnRq0HEZH27sTM6G8NeZ7sS+3YtSYfEiK0cDaNZC8kK9lUIbpxh//NyX+5Ub7neVXQVZ2YWqCi9UGtQZfhdg86TuLP+LsZU6z1Vd/49kbocUdtlfLlb6dNeMGogtAqC4A8DnrCwFutJ/jZFca5ZWeu735IX144P9Mb7L4iGscOt542/85IltYc/XWpYm3QGczwbgFqt7pwofsepdz7H1+V1l4+Iz1VWyJceRztbQc+l/tthuUaMLYx/ZBXfMyzIRchANRD76gdaFygehaXx41BDSjkt9Cvo8XbAkCjKR8cfSU4lhVYfGvgzrFY7D6kdIfZnbgs1ng1/uURWoCGnICn4qg+NCJW+rsqaC2eHNtdceAjYbTv94OzMcM1s3YVEwFmwDyWlwRgmMe6n8xam4TiGDKKzJhlricknDUKjH+AWlxNKkqH3MPzCcktFYbQ==
    username: AgCS3DcDQQQd3BeJglWo30Gi+t5GE4smUFMhS4j/QUIciz7cHvvZ9xen5gQKr8kGB+QToBCYii3RrMvbvOi7CMAmZPR0zxyUdbEUJTtL4kngw/gjV5pfFmy4wTfHlmC7iCQIlzNQRCmw3QPxAInk+swQCZOSkRjAW/o/mHJ6j5eeNDBFMqwEnDtoB27r6mP0JbacnkL7AHZ6pcQHtas3G7351kSFYRXFsDbsm4xJJtup3UOwpGvT0mEdUy9KPlI5fCxLTHlgiKKywyqyaAE98dj0twNmHpDR1Sl08JewkSGg2jXf23JT9xhwAQEHMvAACXQAN3vgMTmkS2FqGZrod4agpbdqPQE4JOxYfcBtORiUszuesa37aQ9Ft0zYBc1QKjs2mdZVChYcZpo1sdhkxzkAqM3rRQRn9X/AYWjDe4KCowou2jvl9NA0GLlc0nHhORsbuvPhwyrmy/v5f0HOnTVxOQE9nw6zl4Io7oSze9gl5ctn0GE6cK6jn75J3LFYFS6uY9sL8OCiMTVQwcG4AQ9RQglL3SlUd+9b3M+Cc2eLf+CaNMvDDax2j6omUpC7jnZ9C3Lk53AVEs9dNiEvO5iwi0xTWBlaCQZ6j/cm4HTVVJPICWAwQmCljlK3NQYR+G3cTStt8LXE862gj9LT5G76YG6/9GQ1QJR0Fe0Pj2RjWUTK3r/qlvstbqtf5He5hSHfnfOuAA==
  template:
    metadata:
      name: demo-secret
      namespace: app
