apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "user.fullname" . | default (basename $dir) }}
  labels:
    {{- include "user.labels" . | nindent 4 | default "app: sock-shop" }}
spec:
  replicas: {{ .Values.replicaCount | default 1 }}
  selector:
    matchLabels:
      app: {{ basename $dir }}
  template:
    metadata:
      labels:
        app: {{ basename $dir }}
    spec:
      containers:
        - name: {{ basename $dir }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}
