---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: app
spec:
  encryptedData:
    password: AgByeEgkLJ9DborNW5ti6eG6L8dJO0peZmmWAdvQe9IYFclTPJ4/jIHSjk7CNGtFdiBxE0VcG84X44cPsXyQpJWtaw5Ptgb2TmShmmCoyP9IrXVJvWe4dbhpCnfO8EOVz+cJPdQms1puihkuNFmrEkvqcn+hUoQgyFrOumLUmaIFRnilUpenDvWNPAuc0wdr3FvPDq1Ge0uETZ1KX4PETOdEWm+sm/Zcah5LgLOBxW+ht+JVLRwYaBwLJovWdLhu9SSaVEH0Mzqp8tsUob0FKVIkRJ5ttPJLOs3x36HS5DBjZF/ipG1tGFhFqUWYOWi7CKLOz4dhuEtUay6A3e0x9bqqJyBV0J7zqoc/JIFAZzWYjaBOLN4yWL4mzsvo/XaMpVStN+Y1ctVcTz7G61HASuXBvd3hoPlerPngChlFD13TrZh/nw4lUHofpnz9nv+F0bvqvtiCjjmZIjkGfgHb84QmTVh50hF6ZbNIbKJgLbq5uN/TBe6p1FE4L2jkeQ6Uj7v83CpCv79oNQFSkl6DueUAIQJESeXBiBwwBoGIkMDDloFQrTVdk7h70W/QvBATzyBGdoOC+HF5Vy0TiVGIPcjHgmpjFL+XRiRoDde+2BU/yuYIK/yhmCn+3JguF5zGJwxs4p2A1Dyv6ZaVWX7ApLne+7wRzbjjSsN7nRm7cwuUTYlWUWL8DQcnkVhcoagrQdPU3wNTkJ1XOq93aw==
    username: AgCZUvECfGiMtkOND8XWVcCK95VVjn8WN//MMu9vHDeGk9iWxZL7lWExD3JqvXh+/Sprt9swf7amZgoJsOltYYw7+4AvnIhGQi9ZvxFG9F8OWEWc8t4FiI2w2S9b5sCn08ZCDWeSmvtJKvuN5ACdg2EYiNmcb8KrL7OE0pnVAP9Ebf0pZG9eGF4tgFHlKr1WcPzBfAvyOdViGJEv2LL0wvCXNaclD3YBH5+DN1ia0wjivSzK6CJyWIleGVxQAENyNOqIUjq0zsr4pUiZ4cAVNaUqrJ23TW7AJv733m+K7Ltu9qsPbmwOfxQvTpKq8q2S+Sk0yCwzuLOj5UcPOCn0GsRQJDUgFvleWqSxlS3vUvqlF6VxCfykEFXrosD8jmk8T+V6w9J2YoiPSy0sr6/QuzodqLj8wvW5a/zU7WQNDa4DjyUYo14vvbRBzVbfn0WmzUskvgraYgd+AMjcHe/N4qCLXr2cgChuq9Q0rYhaabroD4u3NDatJLumA8IN3RaS4BJf4IkcQgikNIyAxRD62ygox5bzYtioz8wdTge5RetGdk3ODmI+jBsvITTOGl1zIOyHgOrrGSz45kCVAxH0bujjjIuoqq/90EK6o1CgrMaqBTF7ywNJZ+QQiIPAqY4Xka2/fKeMn6DhrXOq33WhTGzBxK/oox24LmLLXnSaUqCkr5IfZSe4RXVP29PTJWYnrqPTcIIrAA==
  template:
    metadata:
      name: demo-secret
      namespace: app
