---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgB0KYd5od5CBk1AUnfPs2UdKVRlonoWkSHqG7wz+Be0ZPizDwjdlc49sZGJdDrAScsHdNWNrIADtLTtRhtjnqXqfmAz47Zi4tVRY8/bOn5C2tXNYPrXWoJEQugbw7egJLN/DyFGVugd6YVzzOGGu7uShkaZL/n9vpR4wIWrIc3jrUCP5hwTo4hodxrF86gHI7qNW6LJDNPcwomBQDRePAhB046QLNq/dc5nh0MKkQUZz33A+loQ6Pb/z0Yw/VFPszw0i1KlzS7tVtEKTLtkM5U+v3SnhCcphfASd1Z9vaDd/p5HjS9489oUSgngBK3qpv7mCb7qpBQFElY78bJBcw4v2RLh7mj9mYG95s6biayZP94K40U0jP3M/P+c4njL4khA4n0sVo6ybbmYAhG+McUx5HKRFlAB3J0kTpm7HQEIqdG6FhNyYa4unmLjCW88nf41GlAWYDunTOYmS+qPBsMqVo5qtOt0oyCuq/bJzej6mclzj2Qr+IhhEfiSIMPEloVuKgBErxnHS0h0Ea0Lm6tUUvUSlHSRfakMQ/kpe6CM8ygMerJ3c01JTdONBKTjHqAQ6+Acj6lEU6t4DdwnqVHmNSLX/PTC67LM0+VeYHd+FGLpVuKNgZGqhf1A19gBgPAD93mN4X7gD/tHcnMcVkFX2EzlIy2ZZRZmtGcJKb7X+dbLNzYgT2fH0lHwTNVyURorNXvJ9plEPfz8LZpQcEA=
    username: AgC3EWOWVT3EV+oBcqE1rED2YtDvbWnyS+8gziny5IBgAOvivmqQYKRNSpoTr5yyBNMQW3B8Z62q/p2gFKtc25iokVdMcV4BMlVtPa2VcedsAonv1hFE8IX7iq+0O64CYO+mLV8cNrFIHpNyl8RDkrVAYoRyaPrLybMkP83l48i32unaWiEZ5OMffwp2ZPz8ky78kYMJH0k2Om6N3/WHrKw9EH4jDEIkY6MUvmZuZUGvIg3YnSExh1pf3jPsThn7lx3gFzA6xS6BARP3ntgBx7DlAKjhIUiAqebHPLZH0uwLGSC7wLv1acNm/jKjRxSeX9I/qYPo9PGsW+yYLZBN17Nplb4ZvemLqSuQ2f/JUO8VftY2YC/b5DbxqYWPzKRVpIj+VZncd2Th9HENfOJQ4+tKl0yIuajDTVHE0Xa+SJySOyapBvy10qR8asyTY32J8VCqmpYjJjdoZqU25Y4OMtc1x1uXeR0sh3kgCItE8H2S0YkC4JuS3VY4l4wm01L7LHPmI3eRQNBP4hsckejoMKPJH6UhTAjnieuPkT38K6RwDBESto4TjeME1aa1MwR/FA4kF+zz07KQ40F1+XeYE/kQ+dQSlWkhjmlyh+EWvfVjevdQ7OWa3WqV/Kmw/1rpKDroeSpyXKBlV0q3HJRse7XvJrC5MD8tyzI8AVGP7yGpHVGjso313XgFF9gBrWTLVq2wsSPwac28+jU=
  template:
    metadata:
      name: demo-secret
      namespace: default
    type: Opaque
