---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: demo-secret
  namespace: default
spec:
  encryptedData:
    password: AgA2Zvu9t+yUI3zFwY1K/blkDvGAXZDu8c73BTbOi6O6XjJe395ZsK5DYt86f2C/Pw98k15vE82QpT5ykhgKN3ykSctC3swqIDYg0CasaXROv5oByW4j6vd9wUv2GVxxx6Au6O5IaKXEUZyL4D1619eL1+zosSNdXPMeAiz/8Ipz3aeeKepFHI73xWouj3irC1DNESVSua1KEDx/RsT4YQvM30Na7Qgh+LY/Nsp1pSF+wnXeDaxgaQt9AEh8Jkfo5UHpIlz+qPDQuM6tIqkCs3pZLYYGL6E8pIy79oxYz6r1yls2HkON85z0V3l91mQLp9mYku9Unc0XoYE8rOeG5I77iQSnpf3eCltIxkQU8iBWRmjk3lLna/8LozditWJwCsCuQ42pZ5jvq35Cv8K/SNculK0TFD2rZUj+fYjpATX8dlMCQAk6YyEXoQhkp+H5sr7NfWZ5DQJdHMaKM4DkRFnSdCXoFLpD0kXWOHXgRVmNFTNNN6ubQ5xyAiZuI+02mzHVMryqy/XngAiZ1U0nRX70/aKqKLuExA1ICPeSJbkRS6KpR/sxBoU8FsKGkfk0InbptnBSUowNfk8P0wqLfa6smX4ckWITqjkdg1DtaFWYdA2Euu08qtor9AknRMpIbgZoeuh9PKETp4UP/u4Z40TKHSwCaZPKlumEMr76IplspjMsd14WrH7WMKWVQUJEnn9a/RT32O6WKd2+mekkWHQ=
    username: AgAdpCKhiNTR7tGtFqdLj5U2/NteOZdgOu4oCG62qO9Z7YKa1/+e1xw9frOuEQ8ctU6YDZdS7kqD5RPGm0Yqg71tW1SLtNppjJ4HOyW5d1YO8Qh/qKTicSxM072xwo7N3cqYF0hk/GazIWzl1qJTAkRW6eH+PO1Wb+9bNU8RnH0v9LNAPJ5wELvOamyqSb2055ymSDbCn8y9Q18xkRgwqEl+8I7B7BxgsEsN/da4kZsSIBu8KGOgukB+5BdMd24oSYBWjjZfEa4QRKYksV/BYrrDfSCGrjsOT9F+MmEQ6dmVH5jvmlddZAQD1DN+CSjy5DRYCFEWtSEG9wjS7OiVnWAAhxABRR1rpKfmpfBcPXcAKg/B2FRe3tuuLIMdzd3ASwm1Ce1KSWRKcaDG7jIivPMgaNyjqxi2chM0j6Gbyqnr+fxweiwV8FGdQahpQfslkUFGkZbcrZNwH1AB/ZASwishwJhLmtMnGPPEUmblSeHZH7pA+6WpG5xjLwx8kSoyF8l2l+EiQPENg/EKQuyirpuFxQ2YWb6F+PaFnrPz9VqCGfGYL7O76cH8mCRyNlv31p5d3udKH7A2EFP888fnzA2Rv739u43FiMg3hAYKmRE1krldrROwtjFfHGMlsavcrp2WSooAgwLuL4k2H2NdMoxEE5Qq2zjylDDNl45ljKiP7l6bBF4qgX2ueZPLJ5vsAseIN6W0aXb5GfM=
  template:
    metadata:
      name: demo-secret
      namespace: default
    type: Opaque
